spring:
  datasource:
    url: jdbc:mysql://cdb-a1hhizuq.bj.tencentcdb.com:10118/chong-find?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wenjing0501
  data:
    mongodb:
      uri: mongodb://chongroot:123456@test-env.jincaishuizu.com:27018/chong
  redis:
    host: test-env.jincaishuizu.com
    port: 6379
    password: jincairedis
    timeout: 3600ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接

server:
  port: 10001

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#     控制台打印sql，但是很奇怪
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: mapper\sys\*.xml

#logging:
#  file:
#    name: C:/Users/12287/Desktop/logs/0630.log

##公司 mysql 云数据库
#datasource:
#  url: jdbc:mysql://test-env.jincaishuizu.com:3306/chong-find?useUnicode=true&characterEncoding=utf-8
#  username: root
#  password: root_123456
#  type: com.alibaba.druid.pool.DruidDataSource
#  driverClassName: com.mysql.jdbc.Driver